language: python

python:
  - '2.7'

sudo: required

cache:
  pip: true
  yarn: true
  directories:
    - '$HOME/google-cloud-sdk/'
    - node_modules

notifications:
  - email: false

env:
  # Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Check if gcloud doesn't exist or if there is gcloud update, in which case delete the current installation
  - if ! command -v gcloud || gcloud version 2>&1 | grep -F update; then rm -rf $HOME/google-cloud-sdk; sudo rm -rf /usr/lib/google-cloud-sdk; else echo "Keeping cached Google Cloud SDK"; fi
  # Check if Google Cloud SDK is installed and if not remove remnants and install it
  - if [ ! -d "$HOME/google-cloud-sdk/" ] ; then sudo rm -rf /usr/lib/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Check if Google Cloud SDK is installed *properly* and if not remove remnants and install it
  - if [ ! -f "$HOME/google-cloud-sdk/path.bash.inc" ]; then ls -al $HOME/google-cloud-sdk; rm -rf $HOME/google-cloud-sdk; sudo rm -rf /usr/lib/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH or give some diagnostic info
  - source $HOME/google-cloud-sdk/path.bash.inc || ls -al $HOME/google-cloud-sdk
  - gcloud version
  - node -v
  #
  # eslint requires node ^6.14.0 || ^8.10.0 || >=9.10.0
  - wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - node -v

install:
  - gcloud components install app-engine-python
  - pip install -r requirements.txt
  - yarn install

before_script:
  - yarn global add gulp-cli

script:
  - yarn test
  - gulp deploy --dryrun
