application: gae-init
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- deferred: on
- appstats: on

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Special case for .ttf files needing specific mime_type
# to enjoy gzip encoding/compression from GAE hosting.
# Order is important: this must precede "/p/" static_dir
# See: https://github.com/gae-init/gae-init/issues/53
- url: /p/font/(.*\.ttf)
  static_files: static/font/\1
  upload: static/font/(.*\.ttf)
  mime_type: font/ttf
  expiration: 1000d

- url: /p/
  static_dir: static/
  expiration: 1000d

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?Icon\r
- ^lib/.*
- ^static/src/.*
- ^static/dst/.*
